spring:
  flyway:
    enabled: true
    baselineOnMigrate: false
    validate-on-migrate: false
    outOfOrder: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dev_myapp
    username: dev_user
    password: Reigns@123
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
      idle-timeout: 120000
      max-lifetime: 1200000
      connection-timeout: 30000
      leak-detection-threshold: 20000
      pool-name: HRMSPool
  application:
    name: discovery
    label: main